Feature/product manager
AnalogIO/shifty-webapp pull request #20
Opened 2023-11-12 00:48 UTC by A-Guldborg

Enables adding and updating products through the Shifty app.

Note, a couple things to be discussed:

- Currently only able to shows products that with Visible = True due to how the API is set up. This means that if we add a button to disable a product, it is permanent (can only be reverted in the database). Will need the API to expose products with Visible = False if we want to re-enable products again from Shifty.
- I have (for proof of concept) enabled some gray rows, which is a styling that I wish to apply to "invisible" products. This is of course only possible of the Visible property is exposed as discussed above.
- Currently unable to set Product.UserGroups as this is not exposed by the API. The dropdown is ready but commented out until exposed by the API - which will probably also require a couple bindings/datatypes to be corrected. 

Please give inputs to the above discussion points and/or anything else :)

![image](https://github.com/AnalogIO/shifty-webapp/assets/95026056/52611b9f-30a6-491c-8a34-36e323925eb0)
![image](https://github.com/AnalogIO/shifty-webapp/assets/95026056/1423c6fb-e004-402f-836e-f18da7e31ae3)

2023-11-28 23:31 UTC, A-Guldborg commented
Almost done.

Few things:
1. I can't for the love of God format the text on the multi-select dropdown. Right now, when editing a produc,t, it shows only one value, e.g. "Customer", despite have both Customer and Board as user groups.
2. It seems the PR https://github.com/AnalogIO/analog-core/pull/223 does not work as expected. It does not expose the product user groups in the API on a get request, but I believe that might just be one single line to be added in `coffeecard\CoffeeCard.WebApi\Controllers\v2\ProductsController.cs` in method `MapProductToDto`:
```
AllowedUserGroups = product.ProductUserGroup.Select(e => e.UserGroup)
```

(But I will need to test that before creating such a PR). Once at least the second issue mentioned here is fixed, this PR is ready for review.

2023-12-07 19:21 UTC, A-Guldborg commented on Shifty.App/Components/ProductManager.razor
> +    public System.Security.Claims.ClaimsPrincipal User { get; set; }
Nothing, so I shall have it removed

2023-12-07 19:30 UTC, A-Guldborg commented on Shifty.App/Services/IProductService.cs
> +        Task<Try<ChangedProductResponse>> UpdateProduct(UpdateProductRequest product);
If you say so ┻━┻ ︵ ＼( °□° )／ ︵ ┻━┻

2023-12-28 16:37 UTC, marfavi requested changes
I request all changes in #22 to be merged before continuing, which fixes the horizontal scrolling in the table.

And I renamed your PR :)

2024-01-18 18:02 UTC, marfavi approved these changes
OK

2024-01-18 18:12 UTC, merged